queries/mysite/myauth/urls.py
from django.urls import path
from .views import (login_view,
                    set_cookie_view,
                    get_cookie_view,
                    set_session_view,
                    get_session_view,
                    logout_view,
                    MyLogoutView,
                    AboutMeView,
                    RegisterView,
                    FoobarView,
                    UpdateAvatar,
                    UsersAll,
                    UserDetailsView,
                    HelloView)
from django.contrib.auth.views import LoginView


app_name = "myauth"

urlpatterns = [

    # path("login/", login_view, name="login"),
    path('user-detail/<int:pk>', UserDetailsView.as_view(), name="user_details"),
    path('register/', RegisterView.as_view(), name='register'),
    path('users-all/', UsersAll.as_view(), name='users-all'),
    path('about-me/', AboutMeView.as_view(), name='about-me'),
    path('update/<int:pk>/', UpdateAvatar.as_view(), name="update_avatar"),
    path(
        "login/",
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ),
        name="login"
    ),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("cookie/get/", get_cookie_view, name="get_cookie"),
    path("cookie/set/", set_cookie_view, name="set_cookie"),
    path("session/get/", get_session_view, name="get_session"),
    path("session/set/", set_session_view, name="set_session"),
    path("foo-bar", FoobarView.as_view(), name="foo-bar"),
    path('hello/', HelloView.as_view(), name="hello"),
]

queries/mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView)

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('req/', include('requestdataapp.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'),
         name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'),
         name='redoc'),

    path('api/', include('myapiapp.urls')),
    path('blog/', include('blogapp.urls'))

]
urlpatterns += i18n_patterns(path('admin/', admin.site.urls),
                             path('accounts/', include('myauth.urls')),
                             path('shop/', include('shopapp.urls')),
                             )


if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

queries/mysite/myauth/models.py
from django.db import models
from django.contrib.auth.models import User


def avatar_directory_path(instance: "User", filename: str) -> str:
    return "users/user_{pk}/avatar_image/{filename}".format(
        pk=instance.pk,
        filename=filename,
    )


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(null=True, blank=True, upload_to=avatar_directory_path)

queries/mysite/myauth/forms.py
from django import forms
from .models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar',]

queries/mysite/myauth/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse, HttpRequest, JsonResponse
from django.views.generic import TemplateView, UpdateView, CreateView, ListView, DetailView
from django.urls import reverse_lazy
from .models import Profile
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.views import View
from .forms import ProfileForm
from django.contrib.auth.mixins import UserPassesTestMixin
from django.utils.translation import gettext_lazy as _, ngettext


class HelloView(View):
    welcome_message = _('welcome Hello world')
    def get(self, request: HttpRequest) -> HttpResponse:
        items_str = request.GET.get('items') or 0
        items = int(items_str)
        product_line = ngettext(
            "one product",
            "{count} products",
            items,
        )
        product_line = product_line.format(count=items)


        return HttpResponse(f'<h1>{self.welcome_message}</h1>'
                            f'<h2>{product_line}</h2>')


class UsersAll(ListView):

    context_object_name = 'users'
    template_name = "myauth/users_all.html"
    queryset = Profile.objects.select_related('user')


class AboutMeView(TemplateView):
    template_name = "myauth/about-me.html"


class UpdateAvatar(UserPassesTestMixin, UpdateView):
    model = Profile
    template_name = "myauth/change_avatar.html"

    form_class = ProfileForm

    def test_func(self):
        if self.request.user.profile.id == self.get_object().id or self.request.user.is_staff:
            return True

    def form_valid(self, form):
        response = super().form_valid(form=form)

        return response

    def get_success_url(self):
        return reverse("myauth:users-all")


class UserDetailsView(DetailView):
    template_name = "myauth/user_detail.html"
    queryset = Profile.objects.all()


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'myauth/register.html'
    success_url = reverse_lazy("myauth:about-me")

    def form_valid(self, form):
        response = super().form_valid(form)

        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")

        user = authenticate(request=self.request, username=username, password=password)
        login(request=self.request, user=user)
        return response


def login_view(request: HttpRequest) -> HttpResponse:
    if request.method == "GET":
        if request.user.is_authenticated:
            return redirect('/admin')

        return render(request, 'myauth/login.html')

    username = request.POST["username"]
    password = request.POST["password"]

    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect('/admin/')

    return render(request, 'myauth/login.html', {"error": "Invalid login"})


def logout_view(request: HttpRequest) -> HttpResponse:
    logout(request)
    return redirect(reverse("myauth:login"))


class MyLogoutView(View):
    def get(self, request):
        logout(request)
        return redirect("myauth:login")









@user_passes_test(lambda u: u.is_superuser)
def set_cookie_view(request: HttpRequest) -> HttpResponse:

    response = HttpResponse("Cookie set")
    response.set_cookie("fizz", "buzz", max_age=3600)
    return response


def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get("fizz", "default value")
    return HttpResponse(f"Cookie value: {value!r}")


@permission_required("myauth.view_profile", raise_exception=True)
def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session["foobar"] = "spameggs"
    return HttpResponse("session set!")

@login_required
def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get("foobar", "default")
    return HttpResponse(f"session value: {value!r}!")


class FoobarView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        return JsonResponse({"foo": "bar", "spam": "eggs"})

queries/mysite/myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html' %}

{% block title %}
   About me
{% endblock %}

{% block body  %}
    <h1>User info</h1>
    {% if user.is_authenticated %}
      <h2>Detail</h2>
       {% if user.profile.avatar %}
       <p>
            Avatar: <img src="{{user.profile.avatar.url}}" alt="{{user.profile.avatar.name }}" width="300" height="200">

        </p>
      {% else %}
          <p>You don't have a avatar.</p>
      {% endif %}

      <p>Username: {{ user.username }}</p>
      <p>First name: {{ user.first_name }}</p>
      <p>Last name: {{ user.last_name }}</p>
      <p>Email: {{ user.email }}</p>
      <p>Bio: {{ user.profile.bio }}</p>


      <div>
          {% if user.profile.avatar %}
              <a href="{% url 'myauth:update_avatar' pk=user.profile.pk %}">
                Update avatar</a>
          {% endif %}
      </div>
      <div>
      <a href="{% url 'myauth:users-all' %}">
        Bck to list users
      </a>
      </div>

    {% else %}
       <h2>User is anonymous</h2>
    {% endif %}
{% endblock %}

queries/mysite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>

</head>
<body>
{% block body%}

{% endblock %}
</body>
</html>

queries/mysite/myauth/templates/myauth/change_avatar.html
{% extends 'myauth/base.html' %}

{% block title %}
   Change Avatar
{% endblock %}

{% block body %}
<h1>Change Avatar </h1>
   <form method="post" enctype="multipart/form-data">
       {% csrf_token %}
       {{ form.as_p }}

       <button type="submit">Update</button>
   </form>
{% endblock %}

queries/mysite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
   Login page
{% endblock %}

{% block body %}
   <form method="post">
       {% csrf_token%}
       {{ form.as_p }}

       <button type="submit">Login</button>
   </form>
{% endblock %}

queries/mysite/myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}

{% block title %}
   Register
{% endblock %}

{% block body  %}
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
          <input type="submit" value="Register">

    </form>>
{% endblock %}

queries/mysite/myauth/templates/myauth/user_detail.html
{% extends 'myauth/base.html' %}

{% block title %}
   User Detail
{% endblock %}

{% block body  %}
    <h1>User info</h1>
     {% if object %}
       {% if object.avatar %}
          <p>
            Avatar: <img src="{{object.avatar.url}}" alt="{{object.avatar.name }}" width="300" height="200">

        </p>
       {% else %}
         You don't have a avatar
       {% endif %}

       <p>Username: {{object.user.username}}</p>
       <p>Bio:{{object.bio}}</p>
       <p>First_name: {{object.user.first_name}}</p>
     {% endif %}
     <div>
          {%  if object.user.pk == request.user.pk or request.user.is_staff  %}
              <a href="{% url 'myauth:update_avatar' pk=object.pk %}">
                Update avatar
              </a>
          {% endif%}
      </div>

      <div>
      <a href="{% url 'myauth:users-all' %}">
        Bck to list users
      </a>
      </div>



{% endblock %}

queries/mysite/myauth/templates/myauth/users_all.html
{% extends 'myauth/base.html' %}

{% block title %}
  Users list
{% endblock %}

{% block body %}

  <h1>Users</h1>
  <div>
  {% if object_list %}
    {% for profile in object_list %}
       {% if profile.avatar %}
        <p>
            Avatar: <img src="{{profile.avatar.url}}" alt="{{profile.avatar.name }}" width="300" height="200">

        </p>

       {% else %}
         You don't have a avatar
       {% endif %}
       <a href="{% url 'myauth:user_details' pk=profile.pk%}">
         <p>Username: {{ profile.user.username }}</p>
        </a>
       <p>First_name: {{ profile.user.first_name}}</p>
       <p>Last_name: {{ profile.user.last_name}}</p>
       <p>Bio: {{ profile.bio}}</p>
       <br>



     {% endfor %}
  </div>

  {% endif %}






{% endblock %}