Docs/mysite/myauth/urls.py
from django.urls import path
from .views import (login_view,
                    set_cookie_view,
                    get_cookie_view,
                    set_session_view,
                    get_session_view,
                    logout_view,
                    MyLogoutView,
                    AboutMeView,
                    RegisterView,
                    FoobarView,
                    UpdateAvatar,
                    UsersAll,
                    UserDetailsView,
                    HelloView)
from django.contrib.auth.views import LoginView


app_name = "myauth"

urlpatterns = [

    # path("login/", login_view, name="login"),
    path('user-detail/<int:pk>', UserDetailsView.as_view(), name="user_details"),
    path('register/', RegisterView.as_view(), name='register'),
    path('users-all/', UsersAll.as_view(), name='users-all'),
    path('about-me/', AboutMeView.as_view(), name='about-me'),
    path('update/<int:pk>/', UpdateAvatar.as_view(), name="update_avatar"),
    path(
        "login/",
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ),
        name="login"
    ),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("cookie/get/", get_cookie_view, name="get_cookie"),
    path("cookie/set/", set_cookie_view, name="set_cookie"),
    path("session/get/", get_session_view, name="get_session"),
    path("session/set/", set_session_view, name="set_session"),
    path("foo-bar", FoobarView.as_view(), name="foo-bar"),
    path('hello/', HelloView.as_view(), name="hello"),
]

Docs/mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView)

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('req/', include('requestdataapp.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'),
         name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'),
         name='redoc'),

    path('api/', include('myapiapp.urls')),

]
urlpatterns += i18n_patterns(path('admin/', admin.site.urls),
                             path('accounts/', include('myauth.urls')),
                             path('shop/', include('shopapp.urls')),
                             )


if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

Docs/mysite/shopapp/urls.py
from django.urls import path, include

from rest_framework.routers import DefaultRouter

from .views import (ShopIndexView,
                    # GroupListView,
                    ProductDetails,
                    ProductsList,
                    OrderCreateView,
                    OrderListView,
                    OrderDetailView,
                    OrderUpdateView,
                    OrderDeleteView,
                    ProductCreateView,
                    ProductUpdateView,
                    ProductDeleteView,
                    ProductsDataExportView,
                    OrdersDataExportView,
                    ProductViewSet,
                    OrderViewSet,
                    )

app_name = "shopapp"

routers = DefaultRouter()
routers.register("products", ProductViewSet)
routers.register("orders", OrderViewSet)

urlpatterns = [
    path("", ShopIndexView.as_view(), name="index"),
    # path("groups/", GroupListView.as_view(), name="groups_list"),
    path("products/", ProductsList.as_view(), name="products_list"),
    path("products/export/", ProductsDataExportView.as_view(), name="products-export"),
    path("products/create/", ProductCreateView.as_view(), name="create_product"),
    path("products/<int:pk>/", ProductDetails.as_view(), name="products_details"),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name="products_update"),
    path("products/<int:pk>/archive/", ProductDeleteView.as_view(), name="products_delete"),
    path("orders/", OrderListView.as_view(), name="order_list"),
    path("orders/<int:pk>", OrderDetailView.as_view(), name="order_detail"),
    path("orders/<int:pk>/update", OrderUpdateView.as_view(), name="order_update"),
    path("orders/<int:pk>/delete", OrderDeleteView.as_view(), name="order_delete"),
    path("orders/export/", OrdersDataExportView.as_view(), name="orders-export"),
    path("orders/create/", OrderCreateView.as_view(), name="create_order"),
    path("api/", include(routers.urls))

]

Docs/mysite/shopapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.translation import gettext_lazy as _


def product_preview_directory_path(instance: "Product", filename: str) -> str:
    return "products/product_{pk}/preview/{filename}".format(
        pk=instance.pk,
        filename=filename,
    )


class Product(models.Model):
    """Модель Product представляет товар,
    который можно продавать в интернет магазине.

    Заказы тут: :model:`shopapp.Order`
    """

    class Meta:
        verbose_name = _('Product')
        verbose_name_plural = _('Products')

        ordering = ["name", "price"]
    name = models.CharField(max_length=100, verbose_name=_('name'))
    description = models.TextField(null=False, blank=True, verbose_name=_('description'))
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2,
                                validators=[MinValueValidator(1),
                                            MaxValueValidator(100000000)], verbose_name=_('price'))
    discount = models.SmallIntegerField(default=0, verbose_name=_('discount'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created_at'))
    archived = models.BooleanField(default=False, verbose_name=_('archived'))
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name=_('created_by'))
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directory_path,
                                verbose_name=_('preview'))

    def __str__(self) -> str:
        return f"Product(pk={self.pk}, name={self.name!r})"


def product_images_directory_path(instance: "ProductImage", filename: str) -> str:
    return "products/product_{pk}/images/{filename}".format(
        pk=instance.product.pk,
        filename=filename,
    )


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=product_images_directory_path)
    description = models.CharField(null=False, blank=True, max_length=200)


class Order(models.Model):
    class Meta:
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')

    delivery_address = models.TextField(null=True, blank=True, verbose_name=_('delivery_address'))
    promocode = models.CharField(max_length=20, null=False, blank=True, verbose_name=_('promocode'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created_at'))
    user = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name=_('user'))
    products = models.ManyToManyField(Product, related_name="orders", verbose_name=_('products'))
    receipt = models.FileField(null=True, upload_to='orders/receipt/', verbose_name=_('receipt'), )

Docs/mysite/shopapp/forms.py
from django import forms
from .models import Product, Order
from django.contrib.auth.models import Group





class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = "delivery_address", "promocode", "user", "products"
        widgets = {
            'delivery_address': forms.Textarea(attrs={'rows': 4, 'cols': 15}),
        }


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ["name"]


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "name", "price", "description", "discount", "preview"

    images = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={'allow_multiple_selected': True}),
    )

Docs/mysite/shopapp/views.py
"""
В этом модуле лежат различные наборы представлений.

Разные view интернет магазина: по товарам, заказам итд

"""

from django.shortcuts import render, reverse
from django.http import (
    HttpResponse,
    HttpRequest,
    HttpResponseRedirect,
    JsonResponse)
from timeit import default_timer
from django.contrib.auth.models import Group
from .models import Product, Order, ProductImage
from django.views.generic import (ListView,
                                  DetailView,
                                  DeleteView,
                                  CreateView,
                                  UpdateView)
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.views import View
# from .forms import GroupForm
from .forms import ProductForm
from django.urls import reverse_lazy
from rest_framework.viewsets import ModelViewSet
from rest_framework.generics import ListAPIView
from .serializers import ProductSerializer, OrderSerializer
from rest_framework.filters import SearchFilter, OrderingFilter
from django_filters.rest_framework import DjangoFilterBackend
from drf_spectacular.utils import extend_schema, OpenApiResponse


@extend_schema(description="Product views CRUD")
class ProductViewSet(ModelViewSet):
    """
    Набор представлений дял действий над Product
    Полный CRUD для сущностей товара
    """
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]

    search_fields = ["name", "description"]
    filterset_fields = [
        "name",
        "description",
        "price",
        "discount",
        "archived",
    ]
    ordering_fields = [
        "id",
        "name",
        "price",
        "discount",
    ]

    @extend_schema(

        summary='Get one product by ID',
        description='Retrieves **product** returns 404 if not found',
        responses={
            200: ProductSerializer,
            404: OpenApiResponse(description='Empty response product by id not found'),

        },
    )
    def retrieve(self, *args, **kwargs):
        return super().retrieve(*args, **kwargs)


@extend_schema(description="Order views CRUD")
class OrderViewSet(ModelViewSet):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    filter_backends = [
        DjangoFilterBackend,
        OrderingFilter,
    ]
    filterset_fields = [
        "delivery_address",
        "promocode",
        "user",
        "products",

    ]

    ordering_fields = [
        "id",
        "delivery_address",
        "user",
        "products",

    ]


class ShopIndexView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        products = [
            ('Laptop', 1999),
            ('Desktop', 2999),
            ('Smartphone', 999),
        ]
        context = {
            "time_running": default_timer,
            "products": products,
            "items": 5,

        }
        return render(request, 'shopapp/shop-index.html', context=context)


# class GroupListView(View):
#     def get(self, request: HttpRequest) -> HttpResponse:
#         context = {
#             "form": GroupForm,
#             "groups": Group.objects.prefetch_related('permissions').all(),
#
#         }
#         return render(request=request, template_name='shopapp/groups-list.html', context=context)
#
#     def post(self, request: HttpRequest):
#         form = GroupForm(request.POST)
#         if form.is_valid():
#             form.save()
#
#         return redirect(request.path)


class ProductDetails(PermissionRequiredMixin, DetailView):
    permission_required = ["shopapp.view_product"]
    template_name = "shopapp/product-details.html"
    # model = Product
    queryset = Product.objects.prefetch_related('images')
    context_object_name = "product"


class ProductsList(PermissionRequiredMixin, ListView):
    permission_required = ["shopapp.view_product"]
    template_name = 'shopapp/products-list.html'
    model = Product
    context_object_name = "products"

    queryset = Product.objects.filter(archived=False)


class ProductCreateView(PermissionRequiredMixin, CreateView):

    permission_required = ["shopapp.add_product"]

    model = Product
    fields = "name", "price", "description", "discount", "preview"
    success_url = reverse_lazy("shopapp:products_list")

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form=form)


class ProductUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = ["shopapp.change_product"]
    login_url = 'shopapp/products-list.html'

    model = Product
    # fields = "name", "price", "description", "discount", "preview"
    template_name_suffix = "_update_form"
    form_class = ProductForm

    def form_valid(self, form):
        response = super().form_valid(form=form)
        if form.instance.created_by == self.request.user:
            for image in form.files.getlist('images'):
                ProductImage.objects.create(
                    product=self.object,
                    image=image
                )

            return response
        else:

            return render(request=self.request, template_name="shopapp/update_user_haven't_product.html")

    def get_success_url(self):
        return reverse(
            "shopapp:products_details",
            kwargs={"pk": self.object.pk},
        )


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("shopapp:products_list")

    @extend_schema(
        summary='Create order',
        description='**order** create')
    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)



class OrderCreateView(CreateView):
    model = Order
    fields = "delivery_address", "promocode", "user", "products"
    success_url = reverse_lazy("shopapp:order_list")




class OrderUpdateView(UpdateView):
    model = Order
    fields = "delivery_address", "promocode", "user", "products"
    template_name = "shopapp/order_update_form.html"

    def get_success_url(self, **kwargs):
        return reverse(
            "shopapp:order_detail",
            kwargs={"pk": self.object.pk}
        )


class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy("shopapp:order_list")


class OrderListView(LoginRequiredMixin, ListView):
    queryset = Order.objects.select_related('user').prefetch_related('products')


class OrderDetailView(PermissionRequiredMixin, DetailView):
    permission_required = ["shopapp.view_order"]
    queryset = Order.objects.select_related('user').prefetch_related('products')


class ProductsDataExportView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        products = Product.objects.order_by("pk").all()

        products_data = [{
            "pk": product.pk,
            "name": product.name,
            "price": product.price,
            "archived": product.archived,
            "created_by": product.created_by.id
        }
            for product in products
        ]

        return JsonResponse({"products": products_data})


class OrdersDataExportView(UserPassesTestMixin, View):
    def test_func(self):
        return self.request.user.is_staff

    def get(self, request: HttpRequest) -> JsonResponse:
        orders = Order.objects.order_by('pk').all()

        orders_data = [
            {
                "pk": order.pk,
                "delivery_address": order.delivery_address,
                "promocode": order.promocode,

                "user": order.user.pk,
                "products": [p.pk for p in order.products.all()],
            }
            for order in orders
        ]

        return JsonResponse({"orders": orders_data})

Docs/mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Base title
        {% endblock %}
    </title>
</head>
<body>

{% block body %}
Base body
{% endblock %}

<div>
    {% now 'H:i' %}
</div>
</body>
</html>

Docs/mysite/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Groups List
{% endblock %}

{% block body %}
  <h1>Groups:</h1>
  <div>
    <form method="post">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit">Create</button>
    </form>
  </div>
  <div>
    {% if not groups %}
      <h3>No groups yet</h3>
    {% else %}
      <ul>
        {% for group in groups %}
          <li>
            <div>{{group}}</div>
            <ul>
              {% for permission in group.permissions.all %}
                <li>
                  {{ permission.name }}
                  (<code>{{ permission.codename }}</code>)
                </li>

              {% endfor %}

            </ul>
          </li>
        {% endfor %}
      </ul>

    {% endif %}
  </div>
{% endblock %}

Docs/mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Confirm delete {{ object.name }}
{% endblock %}

{% block body %}
 <h1>Are you sure want to delete order {{object.pk}}  ?</h1>
 <br>
 <div>
     <a href="{% url 'shopapp:order_detail' pk=object.pk %}">Back to order #{{ object.pk }}</a>
 </div>
 <br>
 <div>
     <form method="POST">
         {% csrf_token %}
         {{ form.as_p}}
         <button type="submit">Delete</button>
     </form>
 </div>

{% endblock %}

Docs/mysite/shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
   Order #{{ object.pk }} details
{% endblock %}

{% block body %}
<h1>Order #{{ object.pk }}</h1>
 <div>
      <p>Order by {% firstof object.user.first_name order.user.username %}</p>
      <p>Promocode: <code>{{object.promocode}}</code></p>
      <p>Delivery address: {{object.delivery_address}}</p>
      <div>
          <ul>
              {% for product in object.products.all %}
              <li> {{product.name}} {{product.price}}</li>
              {% endfor %}
          </ul>

      </div>

 </div>
<div>
    <div>
       <a href="{% url 'shopapp:order_list' %}">
        Back to orders list
       </a>>
    </div>
    <br>
    <div>
        <a href="{% url 'shopapp:order_update' pk=object.pk %}">
            Update order #{{ object.pk }}
        </a>>
    </div>
    <br>
    <div>
        <a href="{% url 'shopapp:order_delete' pk=object.pk %}">
            Delete order #{{ object.pk }}
        </a>>
    </div>
    <br>

</div>
{% endblock %}

Docs/mysite/shopapp/templates/shopapp/order_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Create Order
{% endblock %}

{% block body %}
  <h1>Create a new order</h1>
  <div>
    <form method="post">
      {% csrf_token %}

      {{ form.as_p }}
      <button type="submit">
        Create
      </button>
    </form>
  </div>
<br>
<div>
  <a href="{% url 'shopapp:order_list' %}">
    Back to orders list
  </a>
</div>
<br>
{% endblock %}

Docs/mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Order List
{% endblock %}

{% block body %}
 <h1>Orders</h1>
 {% if object_list %}
    <div>
        {% for order in object_list%}
        <div>
            <p><a href="{% url 'shopapp:order_detail' pk=order.pk %}">Details #{{ order.pk }}</a></p>
            <p>Order by {% firstof order.user.first_name order.user.username %}</p>
            <p>Promocode: <code>{{order.promocode}}</code></p>
            <p>Delivery address: {{order.delivery_address}}</p>
            <div>
                <ul>
                    {% for product in order.products.all %}
                    <li> {{product.name}} {{product.price}}</li>
                    {% endfor %}
                </ul>

            </div>

        </div>

        <br>
        {% endfor %}
    </div>

<div>
  <a href="{% url 'shopapp:create_order' %}">
    Back to orders create
  </a>
</div>
<br>
{% else %}
        <div>
            <h3>No orders yet</h3>
        </div>
 {% endif %}
{% endblock %}

Docs/mysite/shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Update order
{% endblock %}

{% block body %}
 <h1>Update order</h1>
 <div>
     <form method="post">
         {% csrf_token %}
         {{ form.as_p}}

         <div>
         <button type="submit">Update</button>
         </div>
     </form>



 </div>
<div>
  <a href="{% url 'shopapp:order_detail' pk=object.pk %}">
    Back to order # {{ object.pk }}
  </a>
</div>
{% endblock %}

Docs/mysite/shopapp/templates/shopapp/product-details.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
  {% translate 'Product Details' %}
{% endblock %}

{% block body %}
 <div>
         {% blocktranslate with product_name=product.name product_price=product.price product_discount=product.discount product_des=product.description product_arch=product.archived product_created_by=product.created_by %}
             <h1>Product <strong> {{ product_name }}</strong></h1>
             <div>
                 <div>Name: <em> {{ product_name }}</em></div>
                 <div>Price: <em> {{ product_price }}</em></div>
                 <div>Discount: <em> {{ product_discount }}</em></div>
                 <div>Description: <em> {{ product_des }}</em></div>
                 <div>Archived: <em> {{ product_arch }}</em></div>
                 <div>Created_by: <em> {{ product_created_by }}</em></div>
             </div>
         {% endblocktranslate %}
 </div>

     {% if product.preview %}
              {% translate 'Preview' %}: <img src="{{product.preview.url}}" alt="{{product.preview.name }}" width="300" height="200">
     {% endif %}
     <h3>{% translate 'Images' %}</h3>
     <div>
         <div>
              {% blocktranslate count image_count=product.images.all|length %}
              There is only one image.
              {% plural %}
              There are {{ image_count }} images.
              {% endblocktranslate %}
         </div>

         {% for img in product.images.all %}

          <div>
              <img src="{{ img.image.url }}" alt="img.image.name" width="300" height="200">
              <div>{{ img.description}}</div>
          </div>
         {% empty %}

         <div>{% translate 'No images upload yet' %}</div>
         {% endfor %}
     </div>

 <div>
     {% url 'shopapp:products_update' pk=product.pk as update_product_url %}
     {% url 'shopapp:products_delete' pk=product.pk as archive_product_url %}
     {% url 'shopapp:products_list' as list_product_url %}
     {% blocktranslate %}
     <div>
        <a href="{{ update_product_url }}">Update product</a>
    </div>
    <div>
        <a href="{{ archive_product_url }}">Archive product</a>
    </div>
    <div>
        <a href="{{ list_product_url }}">Back to product list</a>
    </div>
     {% endblocktranslate %}
 </div>

{% endblock %}

Docs/mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Confirm archive {{ object.name }}
{% endblock %}

{% block body %}
 <h1>Are you sure want to archive {{object.name}}  ?</h1>
 <br>
 <div>
     <a href="{% url 'shopapp:products_details' pk=product.pk %}">Back to product</a>
 </div>
 <br>
 <div>
     <form method="POST">
         {% csrf_token %}
         {{ form.as_p}}
         <button type="submit">Archive</button>
     </form>
 </div>

{% endblock %}

Docs/mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Create product
{% endblock %}

{% block body %}
 <h1>Create product</h1>
 <div>
     <form method="post" enctype="multipart/form-data">
         {% csrf_token %}
         {{ form.as_p}}
         <button type="submit">Create</button>
     </form>
 </div>
<div>
  <a href="{% url 'shopapp:products_list' %}">
    Back to products list
  </a>
</div>
{% endblock %}

Docs/mysite/shopapp/templates/shopapp/product_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Update product
{% endblock %}

{% block body %}

 <h1>Update product</h1>

 <div>
     <form method="post" enctype="multipart/form-data">
         {% csrf_token %}
         {{ form.as_p}}
         <input type="file" name="image" multiple>
         <button type="submit">Update</button>
         {% if errors %}
          {{ errors}}
         {% endif %}
     </form>
 </div>
<div>
  <a href="{% url 'shopapp:products_details' pk=object.pk %}">
    Back to product # {{ object.pk }}
  </a>
</div>


{% endblock %}

Docs/mysite/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
  {% translate 'Products list' %}

{% endblock %}

{% block body %}
 {% if perms.shopapp.view_product %}
  <h1>{% translate 'Products' %}</h1>
  <div>
    {% if products %}
      <div>
          {% blocktranslate count product_count=products|length %}
          There is only one product.
          {% plural %}
          There are {{ product_count }} products.
          {% endblocktranslate %}
      </div>

      <div>
        {% for product in products %}
        <div>
          <p><a href="{% url 'shopapp:products_details' pk=product.pk %}">{% translate 'Name' context 'product name' %}: {{ product.name }}</a></p>
          <p>{% translate 'Price' %}: {{ product.price }}</p>
            {% translate "no discount" as no_discount %}
          <p>{% translate 'Discount' %}: {% firstof product.discount no_discount %}</p>
          <p>{% translate 'Created_by' %}: {{ product.created_by}}</p>
            {% if product.preview %}
              Preview: <img src="{{product.preview.url}}" alt="{{product.preview.name }}" width="300" height="200">
            {% endif %}
        </div>
        <br>

        {% endfor %}

      </div>
      <div>
        <a href="{% url 'shopapp:create_product' %}">
          {% translate 'Back to products create' %}
        </a>
      </div>
    {% else %}
      {% url 'shopapp:create_product' as create_product_url %}
      {% blocktranslate %}
      <h3>'No products yet' </h3>
      <a href="{{ create_product_url }}">
          Product create one
        </a>
      {% endblocktranslate %}
    {% endif %}
  </div>
 {% else %}
    <p>{% translate "You don't have permission to do anything in the foo app." %} </p>
 {% endif %}
 {% if perms.shopapp.add_product %}

  {% else %}
    <p>{% translate "You don't have permission to do anything in the foo app. <br>
        You can't create a product. Add prem in user" %}</p>
 {% endif %}
<br>



{% endblock %}

Docs/mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Shop index
{% endblock %}

{% block body %}
  <h1>Hello Shop Index!</h1>
  <div>
      <ul>
          {% for name, price in products %}
            <li>{{ name }} ({{name|length}}) for ${{ price }}</li>
            {% if name|length_is:'7' %}
              <span>Lucky product</span>
            {% endif %}
          {% empty %}
            No products here
          {% endfor %}
      </ul>
  </div>
 <div>
     <strong>
         You have {{ items }} item{{ items|pluralize:"y, ies" }}
     </strong>
 </div>
  <div>
      Time running: {{ time_running }}
  </div>

  <div>
      {% lorem 3 p random %}
  </div>
{% endblock %}

Docs/mysite/shopapp/templates/shopapp/update_user_haven't_product.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Error page
{% endblock %}

{% block body %}
  <div>
      <p>You can't update someone else's product</p>
  </div>
<div>
  <a href="{% url 'shopapp:products_list' %}">
    Back to products list
  </a>
</div>
{% endblock %}